apiVersion: v1
kind: Service
metadata:
  name: configosaurus
  labels:
    app: configosaurus
spec:
  selector:
    app: configosaurus
  ports:
    - protocol: TCP
      port: 80      # Service port
      targetPort: 8080 # Container port
  type: ClusterIP     # Internal service within the Kubernetes cluster
