version: '3'

dotenv: ['.env', '.env_color']

vars:
  LOCAL_INSTANCE: '{{.CLUSTER_NAME}}'
  KUBECONFIG_FILE: '{{ if eq .LOCAL_CLUSTER "true" }}$HOME/.lima/{{.LOCAL_INSTANCE}}/copied-from-guest/kubeconfig.yaml{{else}}{{.KUBECONFIG_FILE_PATH}}/{{.KUBECONFIG_FILE_NAME}}{{end}}'
  KUBECONFIG: '--kubeconfig {{.KUBECONFIG_FILE}}'
  
includes:
  # Tasks for the lifecycle control for individual labs
  labs:
    taskfile: ./labs
  # Tasks to setup labs to be used with time travel for group workshop
  scenario:
    taskfile: ./scenario
  # Tasks containing resusable tasks
  lib:
    taskfile: ./lib
  # Tasks to manage a local k3s environment
  local: 
    taskfile: ./local
    dir: ./local
  # Tasks to managage tuning Suse Observability server monitors.
  server:
    taskfile: ./suse-observability
    dir: ./suse-observability



