version: '3'

vars:
  CHART_BRONTO: brontosaurus-challenge
  RELEASE_BRONTO: brontosaurus
  
tasks:

  assignment:
    cmds:
      - open ./broken-brontosaurus/assignment.md

  setup: 
    cmds:
      - task: :install-chart
        vars:
          RELEASE: "{{.RELEASE_BRONTO}}"
          CHART: "{{.CHART_BRONTO}}"
          VALUES: |
                  year: "-70000000"

  resolve:
    deps: [setup]
  
  trigger:
    cmds:
      - task: :install-chart
        vars:
          RELEASE: "{{.RELEASE_BRONTO}}"
          CHART: "{{.CHART_BRONTO}}"
          VALUES: |
                  year: "2024"

  teardown:
    cmds:
      - task: :uninstall-chart
        vars:
          RELEASE: "{{.RELEASE_BRONTO}}"
          CHART: "{{.CHART_BRONTO}}"
 
