version: '3'

vars:
  VM_NAME: "challenge-workshop-vm"

includes:
 # Tasks to define sustainability metric bindings
  stackpack:
    taskfile: ./stackpack
    dir: ./stackpack


tasks:
  install-kepler:
    cmds:
      - helm repo add kepler https://sustainable-computing-io.github.io/kepler-helm-chart
      - helm repo update
      - helm upgrade --install --create-namespace --namespace monitoring kepler kepler/kepler {{.KUBECONFIG}} --set serviceMonitor.enabled=false --set serviceMonitor.labels.release=prometheus
  
  deploy-so11y-otel-collector:
    silent: true
    cmds: 
      - |-
        kubectl apply {{.KUBECONFIG}} -n monitoring -f ./otel-collector-rbac.yaml
        cat <<EOF | helm upgrade --install --create-namespace {{.KUBECONFIG}} --namespace monitoring -f - suse {{.HELM_REPO}}/suse-observability-otel-collector 
        apiKey: {{.STS_API_KEY}}
        otlpHost: {{.STS_OTLP}}
        clusterName: {{.CLUSTER_NAME}}
        opentelemetry-collector:
          config:
            receivers:
              prometheus:
                config:
                  scrape_configs:
                  - job_name: 'kepler-metrics'
                    scrape_interval: 3s
                    scheme: http
                    relabel_configs:
                        - action: replace
                          regex: (.*)
                          replacement: $1
                          source_labels:
                          - __meta_kubernetes_pod_node_name
                          target_label: instance
                    kubernetes_sd_configs:
                      - role: service
                        namespaces:
                          own_namespace: true
                        selectors:
                          - role: service
                            label: "app.kubernetes.io/name=kepler"
                          
        EOF

      
  