version: '3'

vars:
  CHART_STEGO: stegostorage
  RELEASE_STEGO: "{{.CHART_STEGO}}"
  NAMESPACE_STEGO: museum
  
tasks:

  assignment:
    cmds:
      - open ./stegostorage/assignment.md

  setup: 
    cmds:
      - task: :install-chart
        vars:
          RELEASE: "{{.RELEASE_STEGO}}"
          CHART: "{{.CHART_STEGO}}" 
          NAMESPACE: "{{.NAMESPACE_STEGO}}" 
          VALUES: |
                  topClass: "yes"

  resolve:
   deps:
      - teardown
   cmds:
      - task: setup
 
  trigger:
    deps:
      - teardown
    cmds:
      - task: :install-chart
        vars:
          RELEASE: "{{.RELEASE_STEGO}}"
          CHART: "{{.CHART_STEGO}}" 
          NAMESPACE: "{{.NAMESPACE_STEGO}}" 
          VALUES: |
                  topClass: "no"
 

  teardown:
    ignore_error: true
    cmds:
      - task: :uninstall-chart
        vars:
          RELEASE: "{{.RELEASE_STEGO}}"
          CHART: "{{.CHART_STEGO}}"
          NAMESPACE: "{{.NAMESPACE_STEGO}}" 
 
