version: '3'

vars:
  PROFILE: instruqt
  GET_FIELD_FUNC: |
    getField() {
      cmd="cat .cache.json | jq '.monitors[] | select(.identifier == \"$1\") | {id: .id, identifier: .identifier, status: .status}' | jq -r '.$2'"
      echo $(eval $cmd)
    }

  OOB_MONITORS:
    - urn:stackpack:prime-kubernetes:shared:monitor:http-response-time
    - urn:stackpack:kubernetes-v2:shared:monitor:kubernetes-v2:pod-cpu-throttling
    - urn:stackpack:kubernetes-v2:shared:monitor:kubernetes-v2:out-of-memory-containers
    - urn:stackpack:kubernetes-v2:shared:monitor:kubernetes-v2:pods-in-waiting-state
    - urn:stackpack:kubernetes-v2:shared:monitor:kubernetes-v2:k8s-service-span-duration
    - urn:stackpack:kubernetes-v2:shared:monitor:kubernetes-v2:pod-span-duration
    - urn:stackpack:open-telemetry:shared:monitor:otel-service-span-duration
    - urn:stackpack:kubernetes-v2:shared:monitor:kubernetes-v2:k8s-service-span-error-ratio
    - urn:stackpack:kubernetes-v2:shared:monitor:kubernetes-v2:available-endpoints-threshold
    - urn:stackpack:kubernetes-v2:shared:monitor:kubernetes-v2:certificate-expiration

  CUSTOM_MONITORS:
    - urn:custom:monitor:certificate-expiration-v2
    - urn:custom:monitor:available-endpoints-threshold-v2
    - urn:custom:monitor:k8s-service-span-error-ratio-v2
    - urn:custom:monitor:otel-service-span-duration-v2
    - urn:custom:monitor:pod-span-duration-v2
    - urn:custom:monitor:k8s-service-span-duration-v2
    - urn:custom:monitor:pods-in-waiting-state-v2
    - urn:custom:monitor:pod-cpu-throttling-v2
    - urn:custom:monitor:out-of-memory-for-containers-v2
    - urn:custom:monitor:http-response-time-v2
    - urn:stackpack:custom:shared:monitor:custom:unbound-pvc

tasks:

  upload-custom-monitors:
    silent: true
    cmds:
      - task: internal-upload-custom-monitors
      - task: disable-oob-monitors

  internal-upload-custom-monitors:
    silent: true
    internal: true
    vars:
      FILES:
        sh: find ./monitors -type f -name '*.yaml'
    cmds:
      - for: { var: FILES }
        cmd: sts monitor apply -f {{.ITEM}} -c {{.PROFILE}}
  
  delete-custom-monitors:
    deps: ["update-cache"]
    silent: true
    cmds:
      - for: { var: CUSTOM_MONITORS }
        cmd: |
            {{.GET_FIELD_FUNC}}
            mId=$(getField '{{.ITEM}}' 'id')
            if [ "${mId}" ]; then
              sts monitor delete -i $mId -c {{.PROFILE}}
              echo "   Identifier '{{.ITEM}}'."
            else
                echo "Monitor '{{.ITEM}}' not found."
            fi

  disable-oob-monitors:
    deps: ["update-cache"]
    cmds:
      - for: { var: OOB_MONITORS }
        task: toggle-monitor 
        vars:
          MONITOR: '{{.ITEM}}'
          STATUS: "ENABLED"
          ACTION: "disable"

  enable-oob-monitors:
    deps: ["update-cache"]
    cmds:
      - for: { var: OOB_MONITORS }
        task: toggle-monitor 
        vars:
          MONITOR: '{{.ITEM}}'
          STATUS: "DISABLED"
          ACTION: "enable"
  
  disable-custom-monitors:
    deps: ["update-cache"]
    cmds:
      - for: { var: CUSTOM_MONITORS }
        task: toggle-monitor 
        vars:
          MONITOR: '{{.ITEM}}'
          STATUS: "ENABLED"
          ACTION: "disable"

  enable-custom-monitors:
    deps: ["update-cache"]
    cmds:
      - for: { var: CUSTOM_MONITORS }
        task: toggle-monitor 
        vars:
          MONITOR: '{{.ITEM}}'
          STATUS: "DISABLED"
          ACTION: "enable"

  # Internal 
  
  toggle-monitor:
    silent: true
    internal: true
    cmds:
      - |
        {{.GET_FIELD_FUNC}}
        status=$(getField '{{.MONITOR}}' 'status')
        if [ $status = "{{.STATUS}}" ]; then
          mId=$(getField '{{.MONITOR}}' 'id')
          sts monitor {{.ACTION}} -i $mId -c {{.PROFILE}}
          echo "   Identifier '{{.MONITOR}}'."
        else
          if [ $status = "" ]; then
            echo "Monitor '{{.MONITOR}} not found'."
          else
            echo "Monitor '{{.MONITOR}}' is already in correct status."
          fi
        fi
    
  update-cache:
    internal: true
    silent: true
    cmds:
    - sts monitor list -c {{.PROFILE}} -o json > .cache.json
      
      