version: '3'

vars:
  CHART_CERT: jurassic-net
  RELEASE_CERT: "{{.CHART_CERT}}"
  NAMESPACE_CERT: museum-jurassic-net
  
tasks:

  assignment:
    cmds:
      - open ./jurassic-net/assignment.md

  setup: 
    cmds:
      - task: :install-chart
        vars:
          RELEASE: "{{.RELEASE_CERT}}"
          CHART: "{{.CHART_CERT}}" 
          NAMESPACE: "{{.NAMESPACE_CERT}}" 
          VALUES: |
                  subscription: "yes"

  trigger:
   cmds:
      - task: :install-chart
        vars:
          RELEASE: "{{.RELEASE_CERT}}"
          CHART: "{{.CHART_CERT}}" 
          NAMESPACE: "{{.NAMESPACE_CERT}}" 
          VALUES: |
                  subscription: "no"
 
  resolve:
    deps:
      - setup

  teardown:
    cmds:
      - task: :uninstall-chart
        vars:
          RELEASE: "{{.RELEASE_CERT}}"
          CHART: "{{.CHART_CERT}}"
          NAMESPACE: "{{.NAMESPACE_CERT}}" 
 
