version: '3'

vars:
  CHART_KIOSK: dino-kiosk
  RELEASE_KIOSK: "{{.CHART_KIOSK}}"
  NAMESPACE_KIOSK: museum-dino-kiosk
  
tasks:

  assignment:
    cmds:
      - open ./dino-kiosk/assignment.md

  setup: 
    cmds:
      - task: :install-chart
        vars:
          RELEASE: "{{.RELEASE_KIOSK}}"
          CHART: "{{.CHART_KIOSK}}" 
          NAMESPACE: "{{.NAMESPACE_KIOSK}}" 
          VALUES: |
                  napping: "no"

  resolve:
    deps: 
      - setup

  trigger:
    cmds:
      - task: :install-chart
        vars:
          RELEASE: "{{.RELEASE_KIOSK}}"
          CHART: "{{.CHART_KIOSK}}"
          NAMESPACE: "{{.NAMESPACE_KIOSK}}" 
          VALUES: |
                  napping: "yes"

  teardown:
    cmds:
      - task: :uninstall-chart
        vars:
          RELEASE: "{{.RELEASE_KIOSK}}"
          CHART: "{{.CHART_KIOSK}}"
          NAMESPACE: "{{.NAMESPACE_KIOSK}}" 
 
