apiVersion: v1
kind: ConfigMap
metadata:
  name: brontoclient-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/version: "0.3.5"
data:
  config.toml: |
    port = 8080
    address = "0.0.0.0"

    [memstress]
    enabled = false

    [[endpoints]]
    uri = "/list"
    delay = "<1ms>"

    [[endpoints.routes]]
    uri = "raptoring/fetch-data"
    delay = "1ms"
    stopOnFail = false

    [[endpoints]]
    uri = "/save"
    delay = "1ms<>2ms"
    errorOnCall = 20
    body.status = "ok"
    body.msg = "data saved"
