apiVersion: apps/v1
kind: Deployment
metadata:
  name: brontoclient
  labels:
    app: brontoclient
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/version: "0.3.5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brontoclient
  template:
    metadata:
      labels:
        app: brontoclient
      annotations:
        checksum/config: '{{ include (print $.Template.BasePath "/brontoclient-cm.yaml") . | sha256sum}}'
    spec:
      containers:
      - name: brontoclient
        image: {{.Values.image}}
        env:
        - name: CONFIG_FILE
          value: /etc/app/config.toml
        ports:
        - containerPort: 8080
        resources:
          {{- toYaml .Values.resources | nindent 12 }} 
        volumeMounts:
        - name: config-volume
          mountPath: /etc/app
      volumes:
      - name: config-volume
        configMap:
          name: brontoclient-config
          items:
          - key: config.toml
            path: config.toml
