apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  labels:
    app: loadgen
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/version: "0.3.5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
      annotations:
        checksum/config: '{{ include (print $.Template.BasePath "/loadgen-cm.yaml") . | sha256sum}}'
    spec:
      containers:
      - name: loadgen
        image: grafana/k6:latest 
        command: 
        - "k6"
        - "run"
        - "/config/script.ts"
        resources: 
          requests:
            memory: "30Mi"
            cpu: "50m"
          limits:
            memory: "35Mi"
            cpu: "75m"                                                                                                                                                                            
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: loadgen-config
          items:
          - key: script.ts
            path: script.ts
