apiVersion: v1
kind: ConfigMap
metadata:
  name: tyrannodb-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/version: "0.3.5"
data:
  config.toml: |
    port = 8080
    address = "0.0.0.0"

    [memstress]
    enabled = false

    [stressng]
    enabled = false

    [[endpoints]]
    uri = "/get"
    delay = "1ms"
    errorOnCall = 0
    body.status = "ok"
    body.msg = "data fetched"

    [[endpoints]]
    uri = "/store"
    delay = "2ms"
    body.status = "ok"
    body.msg = "data stored"
