apiVersion: v1
kind: Service
metadata:
  name: tyrannodb
  labels:
    app: tyrannodb
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/version: "0.3.5"
spec:
  selector:
    app: tyrannodb
  ports:
    - protocol: TCP
      port: 80      # Service port
      targetPort: 8080 # Container port
  type: ClusterIP     # Internal service within the Kubernetes cluster
