# Default values for brontosaurus-challenge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
year: 2024
image:
  repository: gcr.io/google-containers/busybox
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: "broken-brontosaurus"
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

resources: 
  requests:
    memory: "32Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "500m"

command:
  - "/bin/sh"
  - "-c"
  - |
    while true; do
      if [ $YEAR -lt -65000000 ]; then
        echo "I am a brontosaurus"
        sleep 5
      else
        echo "It's the year $YEAR, I am long extinct..."
        exit 1
      fi
    done
