apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stegostorage-pvc
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  {{ if eq .Values.topClass "yes"}}
  storageClassName: {{.Values.storageClassName}}
  {{ else }}
  storageClassName: standard-v2
  {{ end }}