version: '3'
includes:
  brontosaurus:
    taskfile: ./broken-brontosaurus

  forgetasaurus:
    taskfile: ./forgetasaurus

vars:
  NAMESPACE: museum
  repoCheck: |
        set -e
        if [ -z "$CHART" ]; then
          echo "CHART variable required"
          exit 1
        fi
        if [ ! -d "./charts/$CHART" ]; then
          echo "Chart directory does not exist"
          exit 1
        fi
  releaseCheck: |
        if [ -z "$RELEASE" ]; then
          echo "RELEASE variable required"
          exit 1
        fi

tasks:
  lint-chart:
    internal: false
    silent: true
    desc: "task labs:lint -- <chartname>"
    cmds:
      - |
        CHART="{{.CHART}}"
        RELEASE="{{.RELEASE}}"
        {{.repoCheck}}
        cd ./charts/{{.CHART}}
        helm lint . 
    vars:
      CHART: '{{.CLI_ARGS}}'

  # Internal

  uninstall-chart:
    internal: true
    silent: true
    cmds:
      - |
        CHART="{{.CHART}}"
        RELEASE="{{.RELEASE}}"
        {{.repoCheck}}
        {{.releaseCheck}}
        cd ./charts/{{.CHART}}
        helm uninstall --namespace {{.NAMESPACE}} {{.RELEASE}} {{.KUBECONFIG}}

  install-chart:
    internal: true
    silent: true
    cmds:
      - |
        CHART="{{.CHART}}"
        RELEASE="{{.RELEASE}}"
        {{.repoCheck}}
        {{.releaseCheck}}
        BASE_CMD="helm upgrade --install {{.KUBECONFIG}} --namespace {{.NAMESPACE}} --create-namespace"
        cd ./charts/{{.CHART}}
        {{if .VALUES}}
        cat <<EOF | $BASE_CMD -f - {{.RELEASE}} .
        {{.VALUES}}
        EOF
        {{else}}
        $BASE_CMD {{.RELEASE}} .
        {{end}}
    vars:
      VALUES: '{{default "" .VALUES}}'