
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: certosaurus-secret
  labels:
    {{- include "common.labels" . | nindent 4 }}
{{ if eq .Values.subscription "yes"}}
data:
  tls.crt : |-
        {{ .Files.Get "cert/new_cert.pem" | b64enc }}
  tls.key : |-
        {{ .Files.Get "cert/new_key.pem" | b64enc }}
{{ else }}
data:
  tls.crt : |-
        {{ .Files.Get "cert/cert.pem" | b64enc }}
  tls.key : |-
        {{ .Files.Get "cert/key.pem" | b64enc }}
{{ end }}
     
     
