apiVersion: v1
kind: ConfigMap
metadata:
  name: printing-queue-cm
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  config.toml: |
     
     
     # General configuration
     port = 8080
     address = "0.0.0.0"
     serviceName = "Printing Queue"
     logLevel = "info"
     
     # Endpoints
     [[endpoints]]
     uri = "/put"
     delay = "5ms"
     errorOnCall = 0 
     body.status = "success"
     body.msg = "Job added to queue"
     
     [[endpoints]]
     uri = "/get"
     delay = "10ms"
     errorOnCall = 0
     body.status = "success"
     body.msg = "Next job retrieved from queue"
     
     [endpoints.logging]
     before = "Processing [[.Endpoint.Uri]] request"
     beforeLevel = "Info"
     after = "Completed [[.Endpoint.Uri]] request"
     afterLevel = "Info"
     
     
     
     
     [otel.trace]
     enabled = {{.Values.traceEnabled}}
     tracer-name = "printing-queue"
     http-endpoint = "{{.Values.otelHttpEndpoint}}"
     insecure = true

     [otel.metrics]
     enabled = {{.Values.metricsEnabled}}
     http-endpoint = "{{.Values.otelHttpEndpoint}}" 
     insecure = true
