apiVersion: apps/v1
kind: Deployment
metadata:
  name: bronto-burger
  labels:
    service: bronto-burger
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: bronto-burger
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
		{{- include "common.labels" . | nindent 8 }}
        service: bronto-burger 
      annotations:
        checksum/config: '{{ include (print $.Template.BasePath "/bronto-burger-cm.yaml") . | sha256sum}}'
    spec:
      containers:
      - name: bronto-burger
        image: {{.Values.image}}
        env:
        - name: CONFIG_FILE
          value: /etc/app/config.toml
        ports:
        - containerPort: 8080
        {{ if .Values.traceEnabled}}
        resources:
          {{- toYaml .Values.brontoResourcesWhenTracing | nindent 12 }}  
        {{ else }}
        resources:
          {{- toYaml .Values.brontoResources | nindent 12 }} 
        {{ end }} 
        volumeMounts:
        - name: config-volume
          mountPath: /etc/app
      volumes:
      - name: config-volume
        configMap:
          name: bronto-burger-cm
          items:
          - key: config.toml
            path: config.toml
