apiVersion: v1
kind: ConfigMap
metadata:
  name: t-rex-tracker-cm
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  config.toml: |
     
     
     # T-Rex Tracker
     serviceName = "TRex Tracker"
     
     [[endpoints]]
     uri = "/track"
     delay = "{{.Values.defaultLatency}}>"
     body.status = "ok"
     body.msg = "T-Rex safely tracked"
     
     [otel.trace]
     enabled = {{.Values.traceEnabled}}
     tracer-name = "t-rex-tracker"
     http-endpoint = "{{.Values.otelHttpEndpoint}}"  
     insecure = true
     
