apiVersion: apps/v1
kind: Deployment
metadata:
  name: triceratops-transport
  labels:
    service: triceratops-transport
    {{- include "common.labels" . | nindent 4 }}
    {{ if eq .Values.napping "yes"}}
    app.kubernetes.io/version: "0.1.1"
    {{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: triceratops-transport
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
		    {{- include "common.labels" . | nindent 8 }}
        service: triceratops-transport
        {{ if eq .Values.napping "yes"}}
        app.kubernetes.io/version: "0.1.1"
        {{ end }} 
      annotations:
        checksum/config: '{{ include (print $.Template.BasePath "/triceratops-transport-cm.yaml") . | sha256sum}}'
    spec:
      containers:
      - name: triceratops-transport
        image: {{.Values.image}}
        env:
        - name: CONFIG_FILE
          value: /etc/app/config.toml
        ports:
        - containerPort: 8080
        {{ if eq .Values.napping "yes" }}
        resources:
          {{- toYaml .Values.triceratopsResourcesWhenNapping | nindent 12 }}   
        {{ else }}
        {{ if .Values.traceEnabled}}
        resources:
          {{- toYaml .Values.resourcesWhenTracing | nindent 12 }}  
        {{ else }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }} 
        {{ end }} 
        {{ end }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/app
      volumes:
      - name: config-volume
        configMap:
          name: triceratops-transport-cm
          items:
          - key: config.toml
            path: config.toml
